### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by mazzy89** [tahvane1/jablotron80#46] opened 2022-02-20 18:57 UTC
Another error I have found coming from this integration is

```
Unexpected error: Traceback (most recent call last): File "/config/custom_components/jablotron80/jablotron.py", line 709, in read_send_packet_loop records_tmp = self._read_data() File "/config/custom_components/jablotron80/jablotron.py", line 661, in _read_data if data[1 + int(size)] == 0xff: IndexError: index out of range
```

Need to find out how to reproduce it but maybe I get it when I arm the alarm through the home assistant integration.

**Comment by mattsaxon** [comment] 2022-04-27 20:05
I have experienced this myself now and have an idea what the issue is

**Comment by mattsaxon** [comment] 2022-05-08 07:53
Fixed in release 0.27

**Closed by mattsaxon** 2022-05-08 07:53 UTC
Labels: bug, awaiting release
