### ISSUE TITLE
USR-TCp232-304

### ISSUE THREAD

**Issue by thebadboyltz** [tahvane1/jablotron80#166] opened 2024-03-29 15:07 UTC
I have just installed the USR box on my JA card (terminal A and B).
In home assistant I cannot connect to the USR.
Am I doing something wrong?

Home assistant is installed on a VM (ASUSTOR NAS)

the port is 5220 and not 10000 as in the photo

THANKS
![Capture5](https://github.com/tahvane1/jablotron80/assets/153684851/dcadc139-6c2c-428b-b261-f8e31f173bd2)
![Capture3](https://github.com/tahvane1/jablotron80/assets/153684851/861a61a2-c1ef-49e7-8e79-d43cef6d9f88)
![Capture2](https://github.com/tahvane1/jablotron80/assets/153684851/01389abb-b19d-4550-bcfc-5b98f73db8f1)
![Capture1](https://github.com/tahvane1/jablotron80/assets/153684851/5ee493ce-542d-4bd4-8fcd-ac1fc10eef10)
![Capture5](https://github.com/tahvane1/jablotron80/assets/153684851/66fc610a-0504-4f74-824b-f5eb31cad32b)

if I connect from the software and my PC it works

![Capture](https://github.com/tahvane1/jablotron80/assets/153684851/5211a8dd-a19c-4739-be85-570e484e6969)

**Comment by thebadboyltz** [comment] 2024-03-30 06:11
please help is welcome

**Comment by mattsaxon** [comment] 2024-03-30 10:02
I don't have "LINK" or "Similar RFC2217" selected on the "Serial Port" screen

**Comment by mattsaxon** [comment] 2024-03-30 10:03
you should also have selected "JA-80T" on the screen when you setup in HA, not JA-82T

**Comment by thebadboyltz** [comment] 2024-03-31 04:15
really thank you I can connect.
But there is one weird thing, my keyboards are going crazy, they repeatedly display all my sensors as if the keyboard command # was pressed.

To disarm the alarm I must systematically enter the password, or can we configure it by default to avoid having to type it?


last thing, the integration uses a lot of CPU resources at times.
![unnamed (1)](https://github.com/tahvane1/jablotron80/assets/153684851/49ee241e-0e05-4046-9b97-b8f0d6821fec)

**Comment by mattsaxon** [comment] 2024-03-31 08:38
The looping is a duplicate of #167 

The high CPU is a side effect of this.

**Closed by mattsaxon** 2024-03-31 08:38 UTC
Labels: documentation
